### ISSUE TITLE
建议addFile可以返回File实例

### ISSUE THREAD

**Issue by raohuiyong** [dfox89/js-upload-file#10]
使用版本js-upload-file": "^1.2.1"
需求背景：
当我执行addFile()之后，想要立即执行start()，这个时候我只想针对我刚才添加的file进行上传（可能之前的队列里存在被手动暂停的文件，而我不想继续上传），请问我如何获取刚才添加文件的file实例？

**Comment by dfox89** [comment]
已针对这个问题发布了v1.3.0；
解决方式：addFile方法新增了第二个参数，可以传入一个object，传入的值会设置到File实例的meta属性上；可以通过在回调中根据File实例meta属性内的值对文件做不同的逻辑处理；
【感觉这样自由度大一点，可以自行添加各类变量，根据自定义的变量值执行不同的逻辑>.<】
[示例](https://dfox89.github.io/js-upload-file/#/v1/example/eg-file-meta)

**Comment by raohuiyong** [comment]
@dfox89 这思路很好，刚好解决我file文件可能绑定不同参数值的问题。之前我都是申明一个全局变量，每次进行addFile之前进行绑定...每次回调再遍历出来，麻烦得很

**Comment by dfox89** [comment]
@raohuiyong 刚发现这个有个bug，当addFile添加多个文件，且传入了第二个参数，修改其中一个文件的meta属性内的值，会影响其他File上meta内的值；
在v1.3.1修复了>。<

**Comment by raohuiyong** [comment]
@dfox89 一次添加多个文件暂无此需求，目前我只支持选择单个文件。今天升级到1.3.1了，测试暂未发现其它问题。
